apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devx-helloworld-springboot-c0wjk
    backstage.io/kubernetes-id: devx-helloworld-springboot-c0wjk
  name: devx-helloworld-springboot-c0wjk
  namespace: '{{ .Values.config.namespace }}'
spec:
  ports:
  - name: 5050-5050
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: devx-helloworld-springboot-c0wjk
